-- D1 taxonomy corruption patch (Hermes follow-up, 2026-06-16)
-- Run on host: cd web && npx wrangler d1 execute agroeco --remote --file=../backend/d1-taxonomy-patch-2026-06-16.sql --yes

UPDATE entities SET bio_category='plantae', kingdom='Plantae', phylum='Tracheophyta', taxon_class='Magnoliopsida', taxon_order='Solanales', family='Solanaceae', genus='Solanum', gbif_key=2928997 WHERE slug='lycopersicon-esculentum';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='actinonema-hirsutum';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='anthostoma-venetum';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='aspergillus-luteovirescens';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='asterina-aliena';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='asterina-clavuligera';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='asterina-coffeicola';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='asterina-pearsoni';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='asterina-pseudopelliculosa';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='asterina-subreticulata';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='caryospora-coffeae';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='coniophora-arachnoidea';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='cryptodiscus-sambuci';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='diatrypella-citricola';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='diatrypella-herbacea';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='diatrypella-missouriensis';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='diplodina-rhoina';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='fenestella-amorpha';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='flammula-paxiana';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='graphis-persicina';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='hendersonia-citri';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='hendersonia-coffeae';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='hendersonia-cydoniae';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='hendersonia-erianthi';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='hendersonia-galiorum';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='hendersonia-geographica';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='hendersonia-musae';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='odontotrema-ipomoeae';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='ophiobolus-brachyascus';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='ophiobolus-byssicola';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='ophiobolus-consimilis';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='parodiella-circumdata';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='phloeospora-moricola';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='phloeospora-multimaculans';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='ramularia-banksiana';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='ramularia-diervillae';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='ramularia-dioscoreae';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='ramularia-eamesii';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='ramularia-glauca';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='ramularia-helianthi';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='ramularia-impatientis';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='ramularia-lophanthi';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='ramularia-spinaciae';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='sphaerella-panicum';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='sphaerulina-ipomoeae';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='sphaerulina-musae';
UPDATE entities SET bio_category='fungi', kingdom='Fungi' WHERE slug='sphaerulina-oleifolia';
UPDATE entities SET kingdom='Animalia' WHERE slug='acharia-extensa';
UPDATE entities SET kingdom='Animalia' WHERE slug='acleris-comandrana';
UPDATE entities SET kingdom='Animalia' WHERE slug='acraea-necoda';
UPDATE entities SET kingdom='Animalia' WHERE slug='agrestoria-fuscator';
UPDATE entities SET kingdom='Animalia' WHERE slug='aphidoidea-superfamily';
UPDATE entities SET kingdom='Animalia' WHERE slug='archaea-janata';
UPDATE entities SET kingdom='Animalia' WHERE slug='aristotelia-physaliella';
UPDATE entities SET kingdom='Animalia' WHERE slug='astylus-bourgeoisi';
UPDATE entities SET kingdom='Animalia' WHERE slug='astylus-quadrilineatus';
UPDATE entities SET kingdom='Animalia' WHERE slug='caligula-boisduvalii';
UPDATE entities SET kingdom='Animalia' WHERE slug='caligula-japonica';
UPDATE entities SET kingdom='Animalia' WHERE slug='caligula-jonasii';
UPDATE entities SET kingdom='Animalia' WHERE slug='caligula-simla';
UPDATE entities SET kingdom='Animalia' WHERE slug='camtorochys-neulosus';
UPDATE entities SET kingdom='Animalia' WHERE slug='ceratina-ceratinidia-rugosoclypeata';
UPDATE entities SET kingdom='Animalia' WHERE slug='chrysis-venustella';
UPDATE entities SET kingdom='Animalia' WHERE slug='contarinia-squamulicola';
UPDATE entities SET kingdom='Animalia' WHERE slug='cosmoplepa-lintneriana';
UPDATE entities SET kingdom='Animalia' WHERE slug='delta-pryiforme-philippinense';
UPDATE entities SET kingdom='Animalia' WHERE slug='diplolepis-ashmeadi';
UPDATE entities SET kingdom='Animalia' WHERE slug='diplolepis-inconspicuis';
UPDATE entities SET kingdom='Animalia' WHERE slug='diplolepis-lens';
UPDATE entities SET kingdom='Animalia' WHERE slug='edolon-helvum';
UPDATE entities SET kingdom='Animalia' WHERE slug='erythroneurini-young-1952';
UPDATE entities SET kingdom='Animalia' WHERE slug='fasta-fastuosa';
UPDATE entities SET kingdom='Animalia' WHERE slug='graphium-teredon';
UPDATE entities SET kingdom='Animalia' WHERE slug='harmonia-testudinaria';
UPDATE entities SET kingdom='Animalia' WHERE slug='hartigia-trimaculata';
UPDATE entities SET kingdom='Animalia' WHERE slug='hippodamia-amoena';
UPDATE entities SET kingdom='Animalia' WHERE slug='labdia-molybdaula';
UPDATE entities SET kingdom='Animalia' WHERE slug='langsdorfia-lunifera';
UPDATE entities SET kingdom='Animalia' WHERE slug='narycia-reticulata';
UPDATE entities SET kingdom='Animalia' WHERE slug='ophiocoma-wendtii';
UPDATE entities SET kingdom='Animalia' WHERE slug='ophioderma-brevispina';
UPDATE entities SET kingdom='Animalia' WHERE slug='ophiothrix-suensoni';
UPDATE entities SET kingdom='Animalia' WHERE slug='orgyia-anartoides';
UPDATE entities SET kingdom='Animalia' WHERE slug='pachyglossa-agilis';
UPDATE entities SET kingdom='Animalia' WHERE slug='palaeobruchidius-plagiatus';
UPDATE entities SET kingdom='Animalia' WHERE slug='paropsis-atomaria';
UPDATE entities SET kingdom='Animalia' WHERE slug='perizoma-teniata';
UPDATE entities SET kingdom='Animalia' WHERE slug='polia-detracta';
UPDATE entities SET kingdom='Animalia' WHERE slug='pseudautomeris-latus';
UPDATE entities SET kingdom='Animalia' WHERE slug='pupilla-blandi';
UPDATE entities SET kingdom='Animalia' WHERE slug='rhopalomesites-tardyi';
UPDATE entities SET kingdom='Animalia' WHERE slug='semomesia-capanea';
UPDATE entities SET kingdom='Animalia' WHERE slug='sesia-rhynchioides';
UPDATE entities SET kingdom='Animalia' WHERE slug='sesia-scribai';
UPDATE entities SET kingdom='Animalia' WHERE slug='sinoprinceps-xuthus';
UPDATE entities SET kingdom='Animalia' WHERE slug='stelis-stelis';
UPDATE entities SET kingdom='Animalia' WHERE slug='stenoma-staudingerana';
UPDATE entities SET kingdom='Animalia' WHERE slug='succinea-grosvenori';
UPDATE entities SET kingdom='Animalia' WHERE slug='tildenia-glochinella';
UPDATE entities SET kingdom='Animalia' WHERE slug='tildenia-gudmannella';
UPDATE entities SET kingdom='Animalia' WHERE slug='udara-albocaeruleus';
UPDATE entities SET kingdom='Animalia' WHERE slug='udara-dilecta-dilecta';
UPDATE entities SET kingdom='Animalia' WHERE slug='ypsolopha-parallela';
