'use strict';

/**
 * traits_vocabulary seed — single source of truth for trait_name /
 * value_kind / expected_unit / applicable_bio_categories / enum_values
 * / upstream_mappings.
 *
 * Loaded by migration 033 at table-creation time AND by lib/trait-vocabulary.js
 * at extractor-prompt-render time, so the prompt cannot drift from the DB.
 */

const PLANT_TRAITS = [
  { trait_name: 'ph_min', value_kind: 'numeric', expected_unit: 'pH',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Minimum soil pH for healthy growth.',
    upstream_mappings: { trefle: 'ph_minimum' } },
  { trait_name: 'ph_max', value_kind: 'numeric', expected_unit: 'pH',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Maximum soil pH for healthy growth.',
    upstream_mappings: { trefle: 'ph_maximum' } },
  { trait_name: 'optimal_temp_min', value_kind: 'numeric', expected_unit: '°C',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Lower bound of optimal temperature range.',
    upstream_mappings: { trefle: 'minimum_temperature.deg_c' } },
  { trait_name: 'optimal_temp_max', value_kind: 'numeric', expected_unit: '°C',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Upper bound of optimal temperature range.',
    upstream_mappings: { trefle: 'maximum_temperature.deg_c' } },
  { trait_name: 'tolerance_temp_min', value_kind: 'numeric', expected_unit: '°C',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Lower bound of tolerable temperature range (survival, not growth).',
    upstream_mappings: {} },
  { trait_name: 'tolerance_temp_max', value_kind: 'numeric', expected_unit: '°C',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Upper bound of tolerable temperature range.',
    upstream_mappings: {} },
  { trait_name: 'optimal_precip_min', value_kind: 'numeric', expected_unit: 'mm',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Lower bound of optimal annual precipitation.',
    upstream_mappings: { trefle: 'minimum_precipitation.mm' } },
  { trait_name: 'optimal_precip_max', value_kind: 'numeric', expected_unit: 'mm',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Upper bound of optimal annual precipitation.',
    upstream_mappings: { trefle: 'maximum_precipitation.mm' } },
  { trait_name: 'optimal_light', value_kind: 'numeric', expected_unit: '0-10',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Light requirement on Trefle 0-10 scale.',
    upstream_mappings: { trefle: 'light' } },
  { trait_name: 'optimal_soil_moisture', value_kind: 'numeric', expected_unit: '0-10',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Soil moisture preference on Trefle 0-10 scale.',
    upstream_mappings: { trefle: 'soil_humidity' } },
  { trait_name: 'optimal_soil_texture', value_kind: 'numeric', expected_unit: '0-10',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Soil texture preference on Trefle 0-10 scale.',
    upstream_mappings: { trefle: 'soil_texture' } },
  { trait_name: 'nitrogen_fixation', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['plantae'], enum_values: ['none', 'low', 'moderate', 'high'],
    description: 'Symbiotic nitrogen fixation capacity.',
    upstream_mappings: { trefle: 'nitrogen_fixation' } },
  { trait_name: 'days_to_harvest', value_kind: 'numeric', expected_unit: 'days',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Days from sowing/transplant to harvest.',
    upstream_mappings: { trefle: 'days_to_harvest' } },
  { trait_name: 'growth_habit', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['plantae'],
    enum_values: ['tree', 'shrub', 'herb', 'vine', 'graminoid', 'forb', 'subshrub', 'other'],
    description: 'Growth form per Trefle vocabulary.',
    upstream_mappings: { trefle: 'growth_habit' } },
  { trait_name: 'maximum_height_cm', value_kind: 'numeric', expected_unit: 'cm',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Maximum reported plant height.',
    upstream_mappings: { trefle: 'maximum_height.cm' } },
  { trait_name: 'bloom_months', value_kind: 'list', expected_unit: 'month',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Months (1-12) when the plant blooms.',
    upstream_mappings: { trefle: 'bloom_months' } },
  { trait_name: 'fruit_months', value_kind: 'list', expected_unit: 'month',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'Months (1-12) when the plant fruits.',
    upstream_mappings: { trefle: 'fruit_months' } },
  { trait_name: 'toxicity', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['plantae'],
    enum_values: ['none', 'mild', 'moderate', 'severe', 'present'],
    description: 'Toxicity to humans/livestock. Use a severity grade (mild/moderate/severe) ONLY when the source states the degree; if the source merely says "toxic"/"poisonous" with no grade, use "present". Use "none" only when the source explicitly says non-toxic. Do NOT infer a grade the source does not give.',
    upstream_mappings: { trefle: 'toxicity' } },
  { trait_name: 'allelopathic_activity', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['plantae'],
    enum_values: ['none', 'weak', 'moderate', 'strong', 'present'],
    description: 'Reported allelopathic effect on neighboring plants. Use a strength grade (weak/moderate/strong) ONLY when the source states the degree; if the source merely reports allelopathy with no degree, use "present". Do NOT infer a strength the source does not give.',
    upstream_mappings: {} },
  { trait_name: 'native_zones', value_kind: 'list', expected_unit: 'TDWG',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'TDWG region codes where the plant is native.',
    upstream_mappings: { trefle: 'distributions.native' } },
  { trait_name: 'introduced_zones', value_kind: 'list', expected_unit: 'TDWG',
    applicable_bio_categories: ['plantae'], enum_values: null,
    description: 'TDWG region codes where introduced.',
    upstream_mappings: { trefle: 'distributions.introduced' } },
];

const PEST_TRAITS = [
  { trait_name: 'thermal_min', value_kind: 'numeric', expected_unit: '°C',
    applicable_bio_categories: ['invertebrate', 'vertebrate', 'fungi', 'microbe'],
    enum_values: null,
    description: 'Lower lethal/developmental temperature threshold.',
    upstream_mappings: { eol_traitbank: 'http://purl.obolibrary.org/obo/VT_lower_thermal_limit' } },
  { trait_name: 'thermal_max', value_kind: 'numeric', expected_unit: '°C',
    applicable_bio_categories: ['invertebrate', 'vertebrate', 'fungi', 'microbe'],
    enum_values: null,
    description: 'Upper lethal temperature threshold.',
    upstream_mappings: { eol_traitbank: 'http://purl.obolibrary.org/obo/VT_upper_thermal_limit' } },
  { trait_name: 'favorable_temp_min', value_kind: 'numeric', expected_unit: '°C',
    applicable_bio_categories: ['invertebrate', 'vertebrate', 'fungi', 'microbe'],
    enum_values: null,
    description: 'Lower bound of temperature favorable for outbreak/activity.',
    upstream_mappings: {} },
  { trait_name: 'favorable_temp_max', value_kind: 'numeric', expected_unit: '°C',
    applicable_bio_categories: ['invertebrate', 'vertebrate', 'fungi', 'microbe'],
    enum_values: null,
    description: 'Upper bound of temperature favorable for outbreak/activity.',
    upstream_mappings: {} },
  { trait_name: 'favorable_humidity', value_kind: 'range', expected_unit: '%RH',
    applicable_bio_categories: ['invertebrate', 'vertebrate', 'fungi', 'microbe'],
    enum_values: null,
    description: 'Relative humidity range favorable for outbreak/infection.',
    upstream_mappings: {} },
  { trait_name: 'voltinism', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['invertebrate'],
    enum_values: ['univoltine', 'bivoltine', 'multivoltine', 'continuous'],
    description: 'Generations per year.',
    upstream_mappings: {} },
  { trait_name: 'degree_days_base10', value_kind: 'numeric', expected_unit: 'DD°C',
    applicable_bio_categories: ['invertebrate'], enum_values: null,
    description: 'Degree-day accumulation (base 10°C) for one generation.',
    upstream_mappings: {} },
  { trait_name: 'activity_months', value_kind: 'list', expected_unit: 'month',
    applicable_bio_categories: ['invertebrate', 'vertebrate'], enum_values: null,
    description: 'Months (1-12) when the organism is active.',
    upstream_mappings: {} },
  { trait_name: 'diet_breadth', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['invertebrate', 'vertebrate'],
    enum_values: ['monophagous', 'oligophagous', 'polyphagous'],
    description: 'Host specificity.',
    upstream_mappings: {} },
  { trait_name: 'host_range', value_kind: 'list', expected_unit: 'scientific_name',
    applicable_bio_categories: ['invertebrate', 'vertebrate', 'fungi', 'microbe'],
    enum_values: null,
    description: 'Scientific names of host taxa (family/genus/species).',
    upstream_mappings: {} },
  { trait_name: 'crop_damage_type', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['invertebrate', 'vertebrate'],
    enum_values: ['defoliation', 'sap_sucking', 'boring', 'root', 'fruit', 'seed', 'wilting'],
    description: 'Mode of damage to host crop.',
    upstream_mappings: {} },
  { trait_name: 'vulnerable_host_stage', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['invertebrate', 'vertebrate', 'fungi', 'microbe'],
    enum_values: ['seedling', 'vegetative', 'reproductive', 'maturity', 'all'],
    description: 'Crop growth stage most susceptible to this pest/pathogen.',
    upstream_mappings: {} },
  { trait_name: 'dispersal_range', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['invertebrate', 'vertebrate', 'fungi', 'microbe'],
    enum_values: ['local', 'regional', 'long_distance'],
    description: 'Typical dispersal scale.',
    upstream_mappings: {} },
  { trait_name: 'migration_pattern', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['invertebrate', 'vertebrate'],
    enum_values: ['none', 'seasonal', 'nomadic'],
    description: 'Seasonal movement pattern.',
    upstream_mappings: {} },
  { trait_name: 'pest_mobility', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['invertebrate'],
    enum_values: ['sedentary', 'crawling', 'winged', 'flying'],
    description: 'Locomotion mode.',
    upstream_mappings: {} },
];

const PATHOGEN_TRAITS = [
  { trait_name: 'leaf_wetness_hours', value_kind: 'numeric', expected_unit: 'hours',
    applicable_bio_categories: ['fungi', 'microbe'], enum_values: null,
    description: 'Leaf wetness hours required for infection.',
    upstream_mappings: {} },
  { trait_name: 'transmission_mode', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['fungi', 'microbe'],
    enum_values: ['airborne', 'waterborne', 'soilborne', 'seedborne', 'vector', 'contact'],
    description: 'Primary transmission mode.',
    upstream_mappings: {} },
  { trait_name: 'transmission_vector', value_kind: 'list', expected_unit: 'scientific_name',
    applicable_bio_categories: ['fungi', 'microbe'], enum_values: null,
    description: 'Scientific names of vector organisms.',
    upstream_mappings: {} },
  { trait_name: 'survival_structure', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['fungi', 'microbe'],
    enum_values: ['mycelium', 'sclerotium', 'oospore', 'chlamydospore',
                  'conidium', 'teliospore', 'dormant_spore', 'none'],
    description: 'Between-season survival structure.',
    upstream_mappings: {} },
  { trait_name: 'soil_persistence_years', value_kind: 'numeric', expected_unit: 'years',
    applicable_bio_categories: ['fungi', 'microbe'], enum_values: null,
    description: 'Years the pathogen can persist in soil without a host.',
    upstream_mappings: {} },
  { trait_name: 'seed_borne', value_kind: 'boolean', expected_unit: null,
    applicable_bio_categories: ['fungi', 'microbe'], enum_values: null,
    description: 'Whether the pathogen is seed-transmitted.',
    upstream_mappings: {} },
  { trait_name: 'frac_group', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['fungi'],
    enum_values: null, // FRAC code list is large; validated as free text against external map
    description: 'FRAC fungicide-resistance code.',
    upstream_mappings: {} },
  { trait_name: 'pathogen_subtype', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['fungi', 'microbe'], enum_values: null,
    description: 'Race or pathotype designation.',
    upstream_mappings: {} },
];

const BIOCONTROL_TRAITS = [
  { trait_name: 'target_pest_range', value_kind: 'list', expected_unit: 'scientific_name',
    applicable_bio_categories: ['invertebrate', 'microbe'], enum_values: null,
    description: 'Scientific names of pest taxa this biocontrol agent targets.',
    upstream_mappings: {} },
  { trait_name: 'commercial_biocontrol', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['invertebrate', 'microbe'],
    enum_values: ['commercial', 'native_only', 'importable', 'unavailable'],
    description: 'Commercial availability of the biocontrol agent.',
    upstream_mappings: {} },
];

const SOIL_MICROBE_TRAITS = [
  { trait_name: 'soil_health_function', value_kind: 'categorical', expected_unit: null,
    applicable_bio_categories: ['microbe'],
    enum_values: ['nitrogen_fixer', 'phosphorus_solubilizer', 'mycorrhizal',
                  'decomposer', 'other'],
    description: 'Functional role in soil ecosystem.',
    upstream_mappings: {} },
  { trait_name: 'nitrogen_fixation_rate_kg_per_ha_per_yr', value_kind: 'numeric',
    expected_unit: 'kg/ha/yr', applicable_bio_categories: ['microbe'],
    enum_values: null,
    description: 'Reported quantitative nitrogen-fixation rate.',
    upstream_mappings: {} },
];

module.exports = [
  ...PLANT_TRAITS,
  ...PEST_TRAITS,
  ...PATHOGEN_TRAITS,
  ...BIOCONTROL_TRAITS,
  ...SOIL_MICROBE_TRAITS,
];
